### ISSUE TITLE
Add content to Collections page

### ISSUE THREAD

**Issue by ect123** [davidrumseymapcenter/thinking-spatially-toolkit#10]
The Collections page needs some content and organization work. The page to edit is:[ _pages/collections-resources.md](https://github.com/davidrumseymapcenter/thinking-spatially-toolkit/blob/main/_pages/collections-resources.md)

Anything that is formatted as an H2 or smaller in Markdown will be added to the table of contents automatically.

**Comment by ect123** [comment]
It might be worth considering organizing this page around formats, and under each format describing why they might be useful, and where someone would need to go to get more info. 
- Maps and atlases
- Spatial data
- Aerial photos
- Globes?
- Reference books and bibliographies
- more...  ?

**Comment by kristinallarsen** [comment]
Eva Dodsworth organized her 2018 "Research Guide to Cartographic Resources" into the list below. We could start by emulating this, suppressing any sections that haven't we haven't filled out yet. Depending on how much stuff goes into each container we could combine some things into fewer categories. She also has subcategories within most of these sections if they needed to get broken out.

- Atlases: Historic and Thematic
- Topographic, City, and Town Maps
- Railroad Maps
- Geological Maps
- Nautical Charts
- Fire Insurance Plans
- Air Photos
- Bird's-Eye View Maps
- GIS Data Sources
- GIS Subject Guides
- Handbooks and Manuals
- Cartographic and GIS Dictionaries
- Bibliographies
- Gazetteers
