### ISSUE TITLE
Common map and GIS questions

### ISSUE THREAD

**Issue by ect123** [davidrumseymapcenter/thinking-spatially-toolkit#5]
Please add any ideas for basic FAQ style questions below as comments

**Comment by ect123** [comment]
Q: How do I georeference a map?
A: Information about QGIS, ArcGIS Pro, Allmaps, Georeferencer, etc. Maybe GDAL2tiles.py?

**Comment by ect123** [comment]
Q: Who can I talk to about making a map?
A: SGC?

**Comment by dmede** [comment]
Q: How do I learn GIS?

A: SGC resources

**Comment by dmede** [comment]
Q: How do I add my data to Google Maps?
A: Felt maps, ArcGIS Online, Google Earth Web, StoryMaps JS
Note: Assumption is "Google Maps" is not the specific need but this is frequently how the question is posed to me.

**Comment by dmede** [comment]
Q: How do I map a set of addresses?

A: SGC address locator service guide

**Comment by dmede** [comment]
Q: How do I make a map without using GIS software?

A: Felt maps, Google Earth Web...

**Comment by dmede** [comment]
Q: How do I make a map for publishing in a journal article or on a poster?

A: SGC cartography resources.

**Comment by kristinallarsen** [comment]
Q: How do I make comparisons between an historical map and a current / contemporary map?

A: Introduce concept of georeferencing; tools and examples = georeferencer, allmaps, felt, arcgis

**Comment by kristinallarsen** [comment]
Q: How do I find interesting / relevant maps in Stanford's collections?
A: Searchworks, different branches, reach out to librarians

**Comment by kristinallarsen** [comment]
Q: How do I include images of maps in my paper / presentation / digital exhibition / art project?
A: Download links on Searchworks & DR.com; direct linking using IIIF; exporting map images from ArcGIS

**Comment by kristinallarsen** [comment]
Q: How should I identify or cite maps I use in my academic work?
A. Examples; description of acceptable uses

**Comment by kristinallarsen** [comment]
Q: Where can I find datasets to use in a project?
A: ArcGIS, Earthworks, data.gov

**Comment by kristinallarsen** [comment]
Q: How do I layer data on top of a historical map?
A: Concept of georeferencing; ArcGIS, Felt, StoryMap, etc

**Comment by nedorn** [comment]
Q: How do I find a map from davidrumsey.com on Stanford SearchWorks?
A: Search for the "pub list no." from davidrumsey.com in SearchWorks and filter your results to the David Rumsey Map Center. If your search comes up empty, we most likely have not received the map from David yet.

**Comment by kristinallarsen** [comment]
Q: "I just need a map"
A ...
